import { useState } from 'react'
import { profile } from './data/profileData'
import Navbar from './components/Navbar'
import Hero from './components/Hero'
import SeriesRail from './components/SeriesRail'
import TourModal from './components/TourModal'
import Projects from './components/Projects'
import Skills from './components/Skills'
import EngineeringMindset from './components/EngineeringMindset'
import ChatAssistantV2 from './components/ChatAssistantV2'
import Profiles from './components/Profiles'
import Footer